// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.Context;

#nullable disable

namespace WebApplication2.Migrations
{
    [DbContext(typeof(AtmDBContext))]
    [Migration("20221127115158_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication2.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CustomerEmail = "alperen9792@gmail.com",
                            CustomerName = "testUser",
                            CustomerPassword = "testPassword"
                        });
                });

            modelBuilder.Entity("WebApplication2.Entities.CustomerAccount", b =>
                {
                    b.Property<Guid>("CustomerAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<double>("Money")
                        .HasColumnType("float");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransactionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionNumber"));

                    b.HasKey("CustomerAccountId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerAccounts");

                    b.HasData(
                        new
                        {
                            CustomerAccountId = new Guid("e294e7b7-2a44-4f28-acdf-ff906e39c9ed"),
                            CustomerId = 1,
                            Money = 100.0,
                            TransactionDate = new DateTime(2022, 11, 27, 14, 51, 58, 462, DateTimeKind.Local).AddTicks(6142),
                            TransactionNumber = 10000
                        },
                        new
                        {
                            CustomerAccountId = new Guid("70ce9dbc-e6f9-4d2f-a2f7-1051d79f6c5b"),
                            CustomerId = 1,
                            Money = -25.0,
                            TransactionDate = new DateTime(2022, 11, 27, 14, 51, 58, 462, DateTimeKind.Local).AddTicks(6162),
                            TransactionNumber = 10001
                        });
                });

            modelBuilder.Entity("WebApplication2.Entities.CustomerAccount", b =>
                {
                    b.HasOne("WebApplication2.Entities.Customer", "Customer")
                        .WithMany("CustomerAccounts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WebApplication2.Entities.Customer", b =>
                {
                    b.Navigation("CustomerAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
